### ISSUE TITLE
Call a new function GLUE before returning out = MAP(fun)(domain)

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#13]
The problem with `MAP` may arise **many times** for both developers and users ...

1. A general solution is to call a new function `GLUE` or `IDENTIFY` to remove **double** or multiple **points** by identification ... 
3. Use a dictionary with **key** the _truncated coordinate vector_ of points, and as **value** the _array_ of _multiple vertex_ indices.  
5. _Rename_ the second, third, ... instances with the first index and _remove_ the corresponding multiple vectors from their storage structure.
7. Finally, _remove double copies_ of 1-cells and 2-cells, if any.

Apply this filter **before** emitting the **MAP output** ... Always !!!

**Comment by scrgiorgio** [comment]
Please `git pull`
Now you have a function which remove doubles using some tolerance.
Example:

```
precision=1e-4
hpc=GLUE(CUBOID(...),precision)
VIEW(hpc)
```

it's not enabled by default to the MAP function since it can breaks old code.

If you want to run it on a MAP you could do

```
using Plasm

Su0 = BEZIER(S1)([[0, 0, 0], [10, 0, 0]])
Su1 = BEZIER(S1)([[0, 10, 0], [2.5, 10, 3], [5, 10, -3], [7.5, 10, 3], [10, 10, 0]])
Sv0 = BEZIER(S2)([[0, 0, 0], [0, 0, 3], [0, 10, 3], [0, 10, 0]])
Sv1 = BEZIER(S2)([[10, 0, 0], [10, 5, 3], [10, 10, 0]])

fn=COONSPATCH([Su0, Su1, Sv0, Sv1])
domain=Power(INTERVALS(1.0)(10), INTERVALS(1.0)(10))
hpc=MAP(fn)(domain)

precision=1e-4
hpc=GLUE(hpc,precision)
VIEW(hpc)
```

@apaoluzzi please try as close the issue as needed

**Comment by scrgiorgio** [comment]
it's correct it's not breaking most of the MAP examples (actually all HPC/FENVS tests are working just fine).
The problem seems to be arrange3d which is probably more "sensitive" to numerical and topological inconsistencies (even at small scale)? Just guessing here.

**Comment by scrgiorgio** [comment]
fixed by adding GLUE function
