### ISSUE TITLE
Multiple active Viewer objects

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#2]
Il would be of greater benefit to Plasm users  to have more that one active Viewer objects.

Currently, only one Viewer object (1) gets control of execution, and (2) programs cannot continue until it is closed and (3) the control returns to Julia's Main process.   

It would be great if (in some future release) Plasm.jl multiprocessing could open, interact, and close more that one Viewer windows,  possibly under the control of Julia REPL on the terminal.

Great benefits would arise both for the julia software developer (e.g. in debug) and the designer (engineer, architect, etc.) enjoying Plasm.jl

**Comment by scrgiorgio** [comment]
Added another parameter `use_thread` to allow running multiple viewers in parallel.

To enable threading you MUST run julia using:

```bash
julia --project=. --threads=auto 
```


An example using REPL:

```julia
using Plasm
VIEW(CUBOID([1,1,1]), use_thread=true)
VIEWCOMPLEX(lar, use_thread=true)
```

@apaoluzzi  please check and close the issus

**Comment by scrgiorgio** [comment]
it's related to MacOS. See:
https://github.com/JuliaGL/GLFW.jl/issues/233
we have the latest version so we cannot fix it right now.

**Comment by scrgiorgio** [comment]
@apaoluzzi there is not much we can do about it right now. please close the issue
