### ISSUE TITLE
n-ary BoolOps with Hpc Input and OutPut

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#20]
# Algorithm
According to our methods based on _arrangements_, we need four `interface` functions:

```
- UNION : STRUCT() ->  Hpc
- INTERSECTION : STRUCT() ->  Hpc
- DIFFERENCE : STRUCT() ->  Hpc
- XOR : STRUCT() ->  Hpc
```
Any complex Boolean expression 
must have the semantics of a `STRUCT` including one or more such operators.

They are also alias of STRUCT:
```
UNION = STRUCT
INTERSECTION = STRUCT
DIFFERENCE = STRUCT
XOR = STRUCT
```
## First step:  

Transform the _input_ in a list of **Breps** ::Hpc type of dimension $d$ in the sameb reference frame.

If intrinsic and embedding dimension of all terms (`Hpc`) are not equal to $d$ and $d-1$, respectively, give the `ERROR("dimension error in BoolOps", <first childs[i] errored>)`

## Second step

Execute `ARRANGE3D` and get ordered `INNER` `atoms`
as `Boolean string` (binary) `arguments` of  length `LEN(INNER(atoms))`

## Third step

Execute n-ary **Boolean (logical)  operation**,   say  
`UNION || INTERSECTION || DIFFERENCE || XOR 
`on `arguments` string

Return 'solution' string;  convert via `atoms` to `Hpc` return value.

**Comment by scrgiorgio** [comment]
@apaoluzzi  all clear. need to find some time to implement it

**Comment by scrgiorgio** [comment]
fixed
