### ISSUE TITLE
Triangulation probably not needed in TGW algorithm

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#21]
@scrgiorgio:
While working on the book, I wrote:

_In the TGW algorithm,  to process the non-convex boundary faces correctly, we need to port  the non-convex 3D faces in 2D to make a CDT triangulation, using the normal vector computation with the Newell method._ 

Then, I realized that when circularly ordering the faces incident on an edge, we actually _order the normal vectors_, and that the Newell Method is **stable** with respect to the normal (does not get inverted depending on three vertices), and hence **a triangulation is NOT needed**.

I do not understand, within your experimental ARRANGE3D code, if you actually triangulate the faces.  In case, please take care of my remark above,  and let me know.  Thanks.

**Comment by scrgiorgio** [comment]
@apaoluzzi  the new TGW code is not triangulating
