### ISSUE TITLE
Simplest interface to Booleans.  UNION, INTERSECTION, etc. as alias of STRUCT

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#24]
Assume that the input to any Boolean expression is a STRUCT  containing (names of) solid objects and/or other STRUCT assemblies. This input can easily accommodate symbols of Boolean  operations as alias of STRUCT, i.e., may be transformed into a  Hpc  tree (assembly) of any structure and depth. 

When you flatten this Hpc you may get (a) an array of numbered  (LAR) objects and (2) the Boolean (operation symbols from a numbered array of BoolOps aliases of STRUCT) expression,  for the final resolution over set algebra terms, and subexpressions (parenthetical, depending on Hpc traversal), and operation names (UNION, XOR, etc).

- From (1) you may assemble the various V,EV,FE in a single LAR object, and apply ARRANGE3D, to get the whole Geometric Complex (GC = (V, (CF, FE,EV))) with our general method (No CSG tree);

- from (2) you may substitute the proper binary string to each numbered generator term (column of Boolean resolution matrix) .  

Finally you can ask the compilar to resolve the last expression above ... and then continue to associate the binary SOLUTION to its subset of atoms, etc ...

**Comment by scrgiorgio** [comment]
Mi fai un esempio semplice? Mi serve di capire l'interfaccia

**Comment by scrgiorgio** [comment]
The problem here is that UNION/XOR (any bool op) needs to change the conversion from Hpc To LAR. The result is a LAR complex (in general: non-convex cells) and it cannot be transformed back to Hpc. 

Like in your examples: twocubes will be a Lar complex.

**Comment by scrgiorgio** [comment]
solved
