### ISSUE TITLE
Atoms get not shown in "building idea"

### ISSUE THREAD

**Issue by apaoluzzi** [scrgiorgio/Plasm.jl#9]
```
X = GRID([2.4,4.5,-3,4.5,2.4]);
Y = GRID([7,5]);
Z = GRID([3,3]);
building = X * Y * Z;
lar = ARRANGE3D(LAR(building));
VIEWCOMPLEX(lar, explode=[1.4,1.4,1.4], show=["FV","atom"])
```
visualization of atoms is wrong 
Because `copCF` (output from TGW) as well as `lar.C[:CF]` are  wrong !!

I verified that input to function `build_copCF` ls exact,  because it returns 0 for the Euler characteristic:  IFF  there are 18 atoms in `copCF`.   That is exactly the number it should be:  look at the image (wrong!  should be not faces, but atoms) ... 8+8 inner atoms + 2 outer atoms.

<img width="336" alt="image" src="https://github.com/user-attachments/assets/c7361499-dd76-4b76-99a4-f0c3232ed62e">

Please discuss with me the issue. It would be urgent ...
ciao, --a

**Comment by scrgiorgio** [comment]
I think this has been resolved by new TGW implementation
@apaoluzzi please double-check:

```
using Plasm

X = GRID([2.4,4.5,-3,4.5,2.4]);
Y = GRID([7,5]);
Z = GRID([3,3]);
building = X * Y * Z;
lar = ARRANGE3D(LAR(building));
VIEWCOMPLEX(lar, show=["FV"], explode=[1.4,1.4,1.4], title="Faces")
VIEWCOMPLEX(lar, show=["CV"], explode=[1.4,1.4,1.4], title="Atoms")
```

and, if it works, close the issue
